FROM fedora:40

LABEL maintainer="Giordano Salvador <73959795+e3m3@users.noreply.github.com>"
USER root

ENV TERM=xterm-256color
ENV PROJECT_DIR=${HOME}/project
ENV CARGO_ENV=/root/.cargo/env

RUN dnf upgrade -y
RUN dnf install -y rustup gcc llvm llvm-devel python3-lit
RUN dnf clean -y all

ENV RUST_CHANNEL=stable

RUN rustup-init -y
RUN source ${CARGO_ENV} && rustup toolchain install ${RUST_CHANNEL}
RUN source ${CARGO_ENV} && rustup override set ${RUST_CHANNEL}

RUN mkdir -p ${PROJECT_DIR}
RUN mkdir -p ${PROJECT_DIR}/src
RUN mkdir -p ${PROJECT_DIR}/tests

COPY Cargo.toml             ${PROJECT_DIR}/
COPY rust-toolchain.toml    ${PROJECT_DIR}/
COPY LICENSE                ${PROJECT_DIR}/
COPY README.md              ${PROJECT_DIR}/
COPY src                    ${PROJECT_DIR}/src/
COPY tests                  ${PROJECT_DIR}/tests/

WORKDIR ${PROJECT_DIR}
RUN source ${CARGO_ENV} && cargo build
RUN source ${CARGO_ENV} && cargo test -- --nocapture
