[package]
name = "calcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = { version = "=181.1.1", features = ["force-dynamic"] }

[dev-dependencies]
lit = "1.0.4"
